### ISSUE TITLE
Is it really open source?

### ISSUE THREAD

**Issue by fumo-fox** [opensource-emr/hospital-management-emr#100]
Invalid Software License.

Please contact Administrator for License Renewal

License expired on: 2024-Jun-16

**Comment by CreativeOthman** [comment]
you need to run the provided license.sql SQL query file to update your license.

**Comment by opensource-emr** [comment]
yes it is

**Comment by opensource-emr** [comment]
Yes it is check this out.
https://github.com/opensource-emr/hospital-management-emr/issues/99
