### ISSUE TITLE
Admitting Patient from ADT nav requires billing item but how to add a billing item?

### ISSUE THREAD

**Issue by Fakeillusion** [opensource-emr/hospital-management-emr#37]

**Comment by sudreg** [comment]
It is configurable from Parameter. 

We can decide whether to do billing during admission or not. 

if no then change this parameter: 
![image](https://user-images.githubusercontent.com/34830552/173173919-3282d458-575e-4255-a54a-02ffdeaf5ce8.png)

if yes then change this parameter:
![image](https://user-images.githubusercontent.com/34830552/173173908-c30b52f9-fc9d-4934-9683-77bd9f4c5027.png)

**Comment by Fakeillusion** [comment]
I am a little confused. After changing this parameter how will the bill item add to patient when admitting them?

**Comment by sudreg** [comment]
@Fakeillusion : 
Please do Autoadd=false for both items above and check once.
If that doesn't work then pls clean all above input boxes and Update the value.

Let know if that solves your issue.
We'll look further if it doesn't.

**Comment by opensource-emr** [comment]
Closing already answered
