### ISSUE TITLE
Bed Information in Emergency navigation gives failed error

### ISSUE THREAD

**Issue by Fakeillusion** [opensource-emr/hospital-management-emr#39]
![image](https://user-images.githubusercontent.com/107257364/173065828-ab60a9b9-fff0-4fe2-9f04-e06b82998374.png)

**Comment by sudreg** [comment]
This requires debugging.
Kindly check the mentioned api to get the exact error information.
Thanks

**Comment by Fakeillusion** [comment]
Yes I have tried to debug and found that there is no route for "getBedFeature" in the solutions.
