### ISSUE TITLE
VoucherEntry 

### ISSUE THREAD

**Issue by Elm0D** [opensource-emr/hospital-management-emr#49]
when i try to make amanual  Voucher for example as Cost of Goods Consumed ledger
i'm adding aphone bill or Electricity bill Voucher 
i tried many times 
but i have the same error 
!! Entered amounts for voucher are not balanced.!!

![2222](https://user-images.githubusercontent.com/11469105/194044854-3cb04ab0-e56f-4222-a889-4a411661c1c7.png)

not understand why this happen
and how to make it

**Comment by opensource-emr** [comment]
Can you send print screen of the complete entry

**Comment by opensource-emr** [comment]
Closing as no response
