### ISSUE TITLE
Serve issue

### ISSUE THREAD

**Issue by essaanid** [opensource-emr/hospital-management-emr#59]
When i am trying to launch this angular project i am getting this error
ERROR Error: The selector "my-app" did not match any elements in browser console
i need your help please
and thank you in advance

**Comment by opensource-emr** [comment]
Danphe App dones not run through angular. It run through MVC core. MVC Core index.cshtml bootstraps Angular compiled code. You should do ng build and index.cshtml should pull the angular dist binaries. 
Please check Dev documentation https://opensource-emr.github.io/hospital-management-emr//#setup
