### ISSUE TITLE
Cannot restore the DB

### ISSUE THREAD

**Issue by gilbertngandu** [opensource-emr/hospital-management-emr#6]
Hi I want to test your system but I am unable to restore the database.

**Comment by Dushyantsingh-ds** [comment]
-> firstly you create a database or check the database name from app.config file from solution explorer
-> right click on database select 'Tasks'>> 'Import Data'>> 'Data source'>>' Flat file source'
-> Select 'file name' by clicking the 'Browse' Button'>> Next>>next>>Finish.

**Comment by opensource-emr** [comment]
if you can specify error we can look in to it.

**Comment by opensource-emr** [comment]
Closing this as did not hear.

**Comment by merajn** [comment]
I wanted to explore your project , can you tell me in details how to get started as very first i am unable to restore the db, and unable to load 3 projects as well
