### ISSUE TITLE
CurrentFiscalYear is Null

### ISSUE THREAD

**Issue by essaanid** [opensource-emr/hospital-management-emr#61]
When i navigate to accounting module i got this error in browser console, i need your help to fix it, how can i manage fiscal years list? 
i have tried to do that from fiscal years list tab but "new" button is disabled

**Comment by opensource-emr** [comment]
Must be the current year is open and you need to close the accounts. Do check the fiscal year table in SQL Server and try to add a new fiscal calendar and close the previous one.

**Comment by opensource-emr** [comment]
Closing as did not hear
