### ISSUE TITLE
Program Develop Error 

### ISSUE THREAD

**Issue by vigneshrajaganesan** [opensource-emr/hospital-management-emr#63]
Npm install error . 
and ng build --watch got error..
Front error.
Better to provide Installation Documentation.
****

**Comment by exsammy** [comment]
Search environment variable. Edit path on both user and system. add your location of nodejs, add also npm\bin

**Comment by opensource-emr** [comment]
For installation please follow this video . There are like 10 steps  if you do it properly you should be good https://youtu.be/Y-1cc50Cr6Q

**Comment by vigneshrajaganesan** [comment]
Dear team
Good day ,

How to delete existing customer datas ?

Regards
Vignesh Rajaganesan
