### ISSUE TITLE
Angular build is broken

### ISSUE THREAD

**Issue by Coder-Krish** [opensource-emr/hospital-management-emr#65]
![image](https://github.com/opensource-emr/hospital-management-emr/assets/53785538/f8af100f-c9ee-4168-bfbb-08545ae52920)

There are imports from querystring which is breaking the angular build. But cannot identify querystring as any kind of package installed.

There are no references found for the property being imported from querystring as well, removing the imports should solve the problem.

**Comment by Coder-Krish** [comment]
I have submitted a pull request regarding this issue.

**Comment by opensource-emr** [comment]
Thanks i will merge it.
