### ISSUE TITLE
Stuck after login

### ISSUE THREAD

**Issue by exsammy** [opensource-emr/hospital-management-emr#67]
After installing, ran program, logged in with admin/pass123
Next screen says connecting to danphe app....
Loading forever....
Any fix?

**Comment by opensource-emr** [comment]
can you check in dev tools what is the error

**Comment by exsammy** [comment]
Sorry am not a tech savy, where is dev tools?

From Android 12 YahooMail 
 
  On Wed, Sep 27, 2023 at 12:27 PM, ***@***.***> wrote:   


can you check in dev tools what is the error

**Comment by exsammy** [comment]
From Android 12 YahooMail 
 
  On Wed, Sep 27, 2023 at 1:05 PM, Samson ***@***.***> wrote:   Sorry am not a tech savy, where is dev tools?

From Android 12 YahooMail

**Comment by opensource-emr** [comment]
Please follow these steps https://youtu.be/Y-1cc50Cr6Q

**Comment by opensource-emr** [comment]
Closing this hope this video will help https://youtu.be/Y-1cc50Cr6Q
