### ISSUE TITLE
Lab and Imaging requests by doctor does not show under provisional items under billing

### ISSUE THREAD

**Issue by shrikrishna123** [opensource-emr/hospital-management-emr#70]
When we deployed the code from the github repository on our servers, we noticed the following error - 

Lab and Imaging requests by doctor does not show under provisional items under billing

Steps to reproduce - 
- Login as Doctor
- Add Lab and Imaging orders to the patient's profile
- Login as Admin
- Click on Billing.
- Click on Provisional Items.
- Click on Outpatient & ER.

Expected result -
- On clicking Outpatient & ER , the orders from the doctor module done for lab Tests and Imaging will be reflecting under the Billing Column.

Actual result - 
- Lab tests and Imaging orders provided by doctor does not show under the billing column.

**Comment by opensource-emr** [comment]
I can see provision items clearly. Some times the data is not right or master tables are not configured. Do  fix a appointment with the tech support team to check what is not right. You can email us on our email given in website.
If you are a MVC dev please debug

![image](https://github.com/opensource-emr/hospital-management-emr/assets/48054642/c2f7a787-738e-458f-ae6a-0224e943ff1d)

**Comment by opensource-emr** [comment]
Closing
