### ISSUE TITLE
Dispensary doesn't show the medication order added by the doctor for dispatch

### ISSUE THREAD

**Issue by shrikrishna123** [opensource-emr/hospital-management-emr#71]
When we deployed the code from the github repository on our servers, we noticed the following error -

Dispensary doesn't show the medication order added by the doctor for dispatch

Steps to reproduce -

Login as Doctor
Add medication orders to the patient's profile
Login as Admin
Click on Dispensary.
Click on Main Dispensary..
Click on Prescription.
Click on Availability next to the patient.

Expected result -

It will reflect all the medications added by the doctor and its availability as well under dispensary

Actual result -

It does not show the medications added by the doctor.
<img width="522" alt="Screenshot 2023-10-31 at 11 43 12 PM" src="https://github.com/opensource-emr/hospital-management-emr/assets/6744417/9462c4b0-d9cb-4943-a015-42d8fb5a18eb">

**Comment by opensource-emr** [comment]
Doctor module ordering has issues and we are on it.

**Comment by opensource-emr** [comment]
Please check the recent version and look at the current build.
