### ISSUE TITLE
Not able to admit the patient into the hospital for the in-patient flow

### ISSUE THREAD

**Issue by shrikrishna123** [opensource-emr/hospital-management-emr#72]
When we deployed the code from the github repository on our servers, we noticed the following error -

Not able to admit the patient into the hospital for the in-patient flow

Steps to reproduce -

Login as Admin.
Register a new patient and add a new visit.
Click On ADT.
Click on Search Patient.
Click on the “Admit” under the Action Column.
Fill in the Create Admission Form.
Save Admission.

Expected result -

Successful admission message is displayed on the Screen.

Actual result -

No Billing item is found, there must be at least one billing item.

<img width="1293" alt="Screenshot 2023-10-31 at 11 58 04 PM" src="https://github.com/opensource-emr/hospital-management-emr/assets/6744417/89ffe60a-65f1-4b2e-b7d9-8ff7a15b8740">

**Comment by opensource-emr** [comment]
Can you go to console and see what the error or if you can send a print screen
