### ISSUE TITLE
Lab module error

### ISSUE THREAD

**Issue by exsammy** [opensource-emr/hospital-management-emr#75]
When I click on the lab module, it shows but nothing is clicable after that. Below is console screen
![Lab Not working_070703](https://github.com/opensource-emr/hospital-management-emr/assets/145398483/cd55dee6-01a7-427b-9d5d-038ae7654c3e)

**Comment by exsammy** [comment]
I found a painstaking fix
IsDobVerified error - is fixed by changing values from null to false in patients table.

Lab module was fixed by copying values in column BillingTransactionItemId from BIL_TXN_BillingTransactionsItems table to same column in RAD_PatientImagingRequisition table which has null values.

There are over 1100 entries, once copied, lab module and ordering worked like charm.

After that ServiceItemId can also be filled.
This time it's easier to use innerjoin statement on the BillingTransactionItemId since it has values

**Comment by hitenashar** [comment]
The issue has been fixed in the latest version.
