### ISSUE TITLE
Account dropdown list is sometimes obstructed by page elements 

### ISSUE THREAD

**Issue by Agnieszka0544** [opensource-emr/hospital-management-emr#77]
Environment:
Windows 11, Firefox 119.0.1,  Edge 119.0.2151.72
In some tabs (e.g. SocialService, ADT) top right account dropdown list (with logout etc.) is obstructed by some white bars that stretch all the way through.

<details>
<summary>pictures</summary>

![Zrzut ekranu 2023-11-29 190125-zaznaczony](https://github.com/opensource-emr/hospital-management-emr/assets/121827184/b38578ec-2c13-4573-b348-f6bbefbfa6e7)
![Zrzut ekranu 2023-11-23 154002-zaznaczony](https://github.com/opensource-emr/hospital-management-emr/assets/121827184/e1e547f0-6b83-461c-aaf7-535f36e1262b)

</details>

**Comment by exsammy** [comment]
Use Chrome

**Comment by hitenashar** [comment]
The issue has been resolved.
![image](https://github.com/opensource-emr/hospital-management-emr/assets/150318758/ff0d8c65-d0c5-4450-ad4c-93b3313dfeab)
