### ISSUE TITLE
Add Department button gets clipped

### ISSUE THREAD

**Issue by Agnieszka0544** [opensource-emr/hospital-management-emr#78]
Environment:
Windows 11, Firefox 119.0.1, Edge 119.0.2151.72
When you go:
Settings -> Departments -> Manage Department -> Add Department
you can see the button clipped.

<details>
<summary> picture </summary>

![Zrzut ekranu 2023-11-23 162742-zaznaczony](https://github.com/opensource-emr/hospital-management-emr/assets/121827184/f7906fa9-d006-47ec-a7d9-6e6d7657fa92)

</details>

**Comment by hitenashar** [comment]
the above issue has been fixed. 
![image](https://github.com/opensource-emr/hospital-management-emr/assets/150318758/5f5f530b-29ff-4830-afcd-c581c1c80ccc)
