### ISSUE TITLE
Can't open this DanphenEMR web project in VS 2017. Project Unavailable. 

### ISSUE THREAD

**Issue by mmadushanka** [opensource-emr/hospital-management-emr#8]

**Comment by karimkalunga** [comment]
Hi @mmadushanka, same happened to me, DanpheEMR web app couldn't be loaded. I did the following to fix this.

1. Went to C:\Program Files\dotnet\sdk, I had more than one sdk versions installed I deleted all version folders except one with 2.1.519. The web app was written using dotnet sdk 2.1.4xx, but I have not faced any problems using dotnet sdk version 2.1.519.
2. Open Solutions items folder and edit global.json file. Change sdk version from 2.1.4xx to 2.1.519 (or sdk version that you're using).
3. Reload the project.

Hope it helps!

**Comment by mmadushanka** [comment]
Hi @karimkalunga ,  Thanks for your reply, it works for me as well, project could be build,  Now it is getting an error of not determining the process id DanphenEMR.exe. Would you too ?

**Comment by karimkalunga** [comment]
> Hi @karimkalunga , Thanks for your reply, it works for me as well, project could be built, Now it is getting an error of not determining the process id for DanphenEMR.exe. Would you too ?

I didn't get any errors @mmadushanka , few runtime issues though. I've forked the repo and did some few changes. I'd add you just to check it out (if you don't mind) and see if you'd run it on your machine. I'm going to improve dev documentation as well to be easier for someone to get started.

**Comment by mmadushanka** [comment]
Hi @karimkalunga, Thanks for your reply. 
I am getting this error. Please just check this screenshot. 
I am looking around to fix this, If you could also had this ealier and solved please be just let me know how.
![Uploading process id error.png…]()

**Comment by opensource-emr** [comment]
This project uses VS 2019 , Angular 8 and SQL Server express as back end. Check the pre-requistes thanks.
