### ISSUE TITLE
Not able to add address while registering patient

### ISSUE THREAD

**Issue by WiadroMasla** [opensource-emr/hospital-management-emr#80]
Enviroment:
Windows 10, Opera GX

Sequence of steps:
1. Go to Patient/Register Patient/ Address
2. Fill out the address
![image](https://github.com/opensource-emr/hospital-management-emr/assets/56112919/b680b11c-6ffc-46af-a4d6-6d745041c4bd)
3. Click "Add Address"

Expected result:
Changes saved.

Actual result:
Nothing happens, switching tabs causes changes to be discarded.

**Comment by hitenashar** [comment]
Hi there, please use chrome for better experience.  you will be able to add address.
![image](https://github.com/opensource-emr/hospital-management-emr/assets/150318758/b3f242d6-0617-4e2f-8678-a972709a0109)
