### ISSUE TITLE
Notification bell vibrates without notifications

### ISSUE THREAD

**Issue by WiadroMasla** [opensource-emr/hospital-management-emr#81]
Enviroment:
Windows 10, Opera GX

Steps to reproduce:

1. Create new account.
2. Log in using the new account.
3. Finish account configuration.
4. Click "My Notifications"

Expected result:
List contains no notifications, notification bell doesn't vibrate.
OR
List contains unread notifications, notification bell vibrates.

Actual result:
List contains no notifications, notification bell vibrates.

**Comment by opensource-emr** [comment]
Notification comes in certain situations like new patinet , goods arrival .. for configuration updation notificaiton is not enabled. below is a example.
![image](https://github.com/opensource-emr/hospital-management-emr/assets/48054642/29eff839-3c68-45c1-95dd-c398da55a657)
