### ISSUE TITLE
Login form may be vulnerable to SQL injection

### ISSUE THREAD

**Issue by WiadroMasla** [opensource-emr/hospital-management-emr#83]
Enviroment:
Windows 10, Opera GX

Steps to reproduce:
1. Login using following credentials
Username: admin
Password: 1' or 1=1 -- -

Expected result:
"Invalid credentials" message

Actual result:
Connection error ERR_CONNECTION_RESET

This may indicate that code has been injected successfully but the rest of the function didn't yield the result. Creating a successful SQL injection may be possible, especially considering that database scheme with all functions is open source.

**Comment by opensource-emr** [comment]
ERR connection reset is not a sign of SQL injection. If you see the code we are using LINQ and its not dynamic also.
LINQ to SQL passes all data to the database via SQL parameters. So, although the SQL query is composed dynamically, the values are substituted server side through parameters safeguarding against the most common cause of SQL injection attacks.
