### ISSUE TITLE
Going to Laboratory page without any laboratories freezes the page.

### ISSUE THREAD

**Issue by WiadroMasla** [opensource-emr/hospital-management-emr#84]
Enviroment:
Windows 10, Opera GX

Prerequisites:
No labs.

Steps to reproduce:
1. Click "Laboratory"

Expected result:
Case of 0 laboratories is handled.

Actual result:
Laboratory page loads, Active Lab set to none, user unable to switch pages. Refreshing solves the problem.
![image](https://github.com/opensource-emr/hospital-management-emr/assets/56112919/9019ef1e-b763-4418-b16c-ae472c7b0f26)

**Comment by hitenashar** [comment]
Hi there, 

Please use the latest version of the code which we have uploaded. Also use Chrome for better experience. It's working fine in Chrome. 

![image](https://github.com/opensource-emr/hospital-management-emr/assets/150318758/aa8f148e-e128-4f0b-9665-052c056697c8)
