### ISSUE TITLE
Demo credentials are no longer valid

### ISSUE THREAD

**Issue by Agnieszka0544** [opensource-emr/hospital-management-emr#85]
Credentials provided in README file [here](https://github.com/opensource-emr/hospital-management-emr/blob/master/README.md?plain=1#L13C2-L13C2) give "Invalid credentials !" error on login attempt.
That was on the new link: http://202.51.74.168:302

**Comment by hitenashar** [comment]
The issue has been resolved please try again.

**Comment by Agnieszka0544** [comment]
Thanks, it works now!
