### ISSUE TITLE
Searching for a patient in the death certificate form doesn’t work

### ISSUE THREAD

**Issue by Agnieszka0544** [opensource-emr/hospital-management-emr#87]
Environment:
Windows 11; Firefox 120.0.1, Chrome 120.0.6099.71
When you enter the hospital number or patient name in the search bar on the death certificate creation form, “No Result Found” is displayed.

<details>
<summary>video</summary>

https://github.com/opensource-emr/hospital-management-emr/assets/121827184/fe5da763-0918-4d8f-b05a-5ac6d506ebc9
</details>

**Comment by hitenashar** [comment]
@Agnieszka0544 Firstly it has to be an inpatient. and then must be discharged as dead, then that patient will appear on the MR inpatient list. Then again, we have to declare him dead, after which we will be able to add death details. 
![image](https://github.com/opensource-emr/hospital-management-emr/assets/150318758/2e853253-74e1-45b0-8194-25825c7cadd3)
![image](https://github.com/opensource-emr/hospital-management-emr/assets/150318758/d736a4fb-490f-4b40-abd1-ed6f2a6a0fc4)
