### ISSUE TITLE
Pharmacy may not be needed to transfer items between items

### ISSUE THREAD

**Issue by WiadroMasla** [opensource-emr/hospital-management-emr#90]
In the current version, whenever item transfer between Dispensaries is created, Pharmacy is needed in order to approve the transfer. In some situations direct transfer may be easier. There should be an option to make a direct transfer (for example in a form of a checkbox when creating one), which would change the transfer process from:
(Dispensary1) Create transfer -> (Pharmacy) Accept transfer -> (Dispensary2) Receive transfer
to
(Dispensary1) Create transfer -> (Dispensary2) Receive transfer

**Comment by hitenashar** [comment]
@WiadroMasla Please note that all the items in the dispensary come from the pharmacy. And pharmacy keeps a check on the dispensary's inventory. That is why we don't have any direct transfer from one dispensary to another. Hence pharmacy approval is needed.
