### ISSUE TITLE
New Service Item form doesn't fit on the page

### ISSUE THREAD

**Issue by Agnieszka0544** [opensource-emr/hospital-management-emr#94]
Environment: Windows 11; Firefox 120.0.1, Chrome 120.0.6099.110, Edge 120.0.2210.61
When you go:
Settings -> Billing -> Service Items -> New Service Item
Price Settings section is too large on default 100% zoom value. 

<details>
<summary> picture </summary>

<img width="960" alt="Zrzut ekranu 2023-12-14 224130" src="https://github.com/opensource-emr/hospital-management-emr/assets/121827184/90297bce-2d0d-4dd6-90bb-3a35754b39ec">

</details>

**Comment by hitenashar** [comment]
@Agnieszka0544 Please check your internal settings. It works fine at our end. 
![image](https://github.com/opensource-emr/hospital-management-emr/assets/150318758/1cc88028-a04d-4b4f-8074-ae6af79f3171)
