### ISSUE TITLE
Pharmacy sale and billing

### ISSUE THREAD

**Issue by RaphaelAbila** [opensource-emr/hospital-management-emr#95]
Once a prescription is dispatched my assumption is you go to dispensary>sale>sale and conduct a sale to that patient, however there is no option to sell multiple items at ago, then also for a single product throws a validation error of invalid quantity and item once you select a medicine or type just a single letter, the error is thrown and you can't progress in the latest version

**Comment by hitenashar** [comment]
@RaphaelAbila you may visit the given below for the same. Also, just so you know, it is allowing multiple quantities for the sale. 
![image](https://github.com/opensource-emr/hospital-management-emr/assets/150318758/cf8e8be8-3ea6-4000-a4b5-8c8876d533e6)


The link:  http://202.51.74.168:302/Home/Index#/Dispensary/Sale/New
