### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Mcxm2202** [opensource-emr/hospital-management-emr#99]
Please contact Administrator for License Renewal

License expired on: 2024-Jun-16

i have got this response can you help guys
![Screenshot 2024-07-09 153024](https://github.com/opensource-emr/hospital-management-emr/assets/100447746/a84b9ecc-908a-4ad9-b5ce-50345b1d1eb0)

**Comment by Mcxm2202** [comment]
Thanks to support team here 
I was given this query to run in the main database 

SQL Update CORE_CFG_Parameters set ParameterValue='{"LicenseType":"Full","StartDate":"iC0fmfp/49Gy7FopJ3MLKA==", "EndDate":"rHl5kYYkqQpI8kL+4mRekA==","ExpiryNoticeDays":"9g+iHewEXJE="}' where ParameterGroupName = 'TenantMgnt' and ParameterName = 'SoftwareLicense'

**Comment by opensource-emr** [comment]
Closing it we will be creating an updated video for the same.

**Comment by Mcxm2202** [comment]
IS THERE A WAY I CAN GET A NEW DATA BASE VERSION WHERE I CAN START OFF BY MY SELF

**Comment by Mcxm2202** [comment]
I MEAN WHEN YOU TRY TO WORK WITH THE INITIAL INFORMATION YOU CANNOT REMOVE OR DELETE IT THROUGH THE APP ALSO IT THERE NON APPEARING CONSTRAINTS IN THE DATABASE

**Comment by cherryash100** [comment]
how to use licience
